### ISSUE TITLE
How to make it a offline editor

### ISSUE THREAD

**Issue by Kobra299** [ignis05/baro-save-editor#3]
I was hoping you could expained the information about how to use it as offline as your readme does not really help to much

**Comment by ignis05** [comment]
It uses [PWA](https://en.wikipedia.org/wiki/Progressive_web_application) feature: when visiting the save editor website your browser should give you an option to "install" the website as standalone application. How this option looks and where it is can be different, based on which browser you use, but usually somewhere near the address bar or when right-clicking on the tab it should give you an option to "install" it.
