### ISSUE TITLE
can't change max mission count.

### ISSUE THREAD

**Issue by esirprus** [ignis05/baro-save-editor#7]
![image](https://user-images.githubusercontent.com/44423036/211204623-3e88c8dd-33b7-4f08-957a-cb4eac8a1eb2.png)
at before you can simply change max mission count by this, but now you have to edit Gamesession.xml.
I guess something is renamed because i can see maxmissioncount and MaxMissionCount in Gamesession.xml.
Also noticed radiationenabled and RadiationEnabled.
change maxmissioncount's value will do nothing, but change MaxMissionCount will work.
![image](https://user-images.githubusercontent.com/44423036/211204794-f62df32d-ca7e-450c-8b75-dc9c5e3a8258.png)

**Comment by ignis05** [comment]
Thanks for the report, it appears that the latest game update made some changes in capitalisation of some attributes, which caused this issue.
The fix should be ready soon.

**Comment by esirprus** [comment]
Thank you so much for the quick update!
